name: Deno CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup GCC 12
        run: |
          sudo apt update
          sudo apt install gcc-12
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 110

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Compile secret sharing lib
        working-directory: ./native
        run: |
          gcc -c -fPIC -o bridge.o bridge.c
          gcc -c -fPIC -o secret_sharing.o secret_sharing.c
          gcc -shared -W -o libsecretsharing.so bridge.o secret_sharing.o

      - name: Verify formatting
        working-directory: ./deno
        run: deno fmt --check .

      - name: Run linter
        working-directory: ./deno
        run: deno lint .

      - name: Run tests
        working-directory: ./deno
        run: deno test -A --unstable --coverage=cov_profile

      - name: Print coverage
        working-directory: ./deno
        run: deno coverage cov_profile
